name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "Done - bye!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second printing
        run: echo "this is my new workflow file"
      - name: Print second greeting
        run: echo "time to say final goodbye!"
      
      
    
