name: first workflow
on: worflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "Done - bye"
      
      
    
